library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(shiny)
options(gsubfn.engine="R")
library("readxl")
library("openxlsx")
library(tmap)
source("https://raw.githubusercontent.com/jaanos/APPR-2019-20/master/lib/uvozi.zemljevid.r")
library(ggplot2)
library(dplyr)
library(readr)

